// GENERATED by tools/gen_assets.py (player-skin layout + the scythe from blender/scythe_boxes.json).
// Do not edit by hand: change the spec in the script and run it again.
package com.entity303.client.render;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeDeformation;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

public final class Entity303Geometry {
	private Entity303Geometry() {
	}

	public static LayerDefinition createBodyLayer() {
		MeshDefinition mesh = new MeshDefinition();
		PartDefinition root = mesh.getRoot();

		PartDefinition head = root.addOrReplaceChild("head", CubeListBuilder.create()
			.texOffs(0, 0).addBox(-4F, -8F, -4F, 8F, 8F, 8F)
			.texOffs(32, 0).addBox(-4F, -8F, -4F, 8F, 8F, 8F, new CubeDeformation(0.5F)),
			PartPose.offset(0F, 0F, 0F));

		PartDefinition body = root.addOrReplaceChild("body", CubeListBuilder.create()
			.texOffs(16, 16).addBox(-4F, 0F, -2F, 8F, 12F, 4F)
			.texOffs(16, 32).addBox(-4F, 0F, -2F, 8F, 12F, 4F, new CubeDeformation(0.25F)),
			PartPose.offset(0F, 0F, 0F));

		PartDefinition right_arm = root.addOrReplaceChild("right_arm", CubeListBuilder.create()
			.texOffs(40, 16).addBox(-3F, -2F, -2F, 4F, 12F, 4F)
			.texOffs(40, 32).addBox(-3F, -2F, -2F, 4F, 12F, 4F, new CubeDeformation(0.25F)),
			PartPose.offset(-5F, 2F, 0F));

		PartDefinition scythe_pivot = right_arm.addOrReplaceChild("scythe_pivot", CubeListBuilder.create(),
			PartPose.offset(-1F, 10.5F, 0F));

		PartDefinition scythe = scythe_pivot.addOrReplaceChild("scythe", CubeListBuilder.create()
			.texOffs(64, 0).addBox(-0.7F, -12.6F, -0.7F, 1.4F, 22.4F, 1.4F)
			.texOffs(75, 0).addBox(-1.05F, -2.1F, -1.05F, 2.1F, 4.9F, 2.1F)
			.texOffs(91, 0).addBox(-0.7F, 9.8F, -0.7F, 1.4F, 1.4F, 1.4F)
			.texOffs(91, 0).addBox(-1.4F, -14F, -1.4F, 2.8F, 1.4F, 2.8F)
			.texOffs(84, 0).addBox(-0.7F, -16.8F, 0F, 1.4F, 2.8F, 0.7F)
			.texOffs(84, 0).addBox(-0.7F, -18.9F, -0.7F, 1.4F, 4.9F, 0.7F)
			.texOffs(84, 0).addBox(-0.7F, -18.2F, -1.4F, 1.4F, 4.2F, 0.7F)
			.texOffs(110, 0).addBox(-0.35F, -14F, -2.1F, 0.7F, 0.7F, 0.7F)
			.texOffs(84, 0).addBox(-0.7F, -16.1F, -2.1F, 1.4F, 2.1F, 0.7F)
			.texOffs(103, 0).addBox(-0.7F, -16.8F, -2.1F, 1.4F, 0.7F, 0.7F)
			.texOffs(110, 0).addBox(-0.35F, -14F, -2.8F, 0.7F, 0.7F, 0.7F)
			.texOffs(84, 0).addBox(-0.7F, -16.8F, -2.8F, 1.4F, 2.8F, 0.7F)
			.texOffs(103, 0).addBox(-0.7F, -17.5F, -2.8F, 1.4F, 0.7F, 0.7F)
			.texOffs(110, 0).addBox(-0.35F, -14F, -3.5F, 0.7F, 0.7F, 0.7F)
			.texOffs(84, 0).addBox(-0.7F, -17.5F, -3.5F, 1.4F, 3.5F, 0.7F)
			.texOffs(103, 0).addBox(-0.7F, -18.2F, -3.5F, 1.4F, 0.7F, 0.7F)
			.texOffs(110, 0).addBox(-0.35F, -14.7F, -4.2F, 0.7F, 0.7F, 0.7F)
			.texOffs(84, 0).addBox(-0.7F, -17.5F, -4.2F, 1.4F, 2.8F, 0.7F)
			.texOffs(103, 0).addBox(-0.7F, -18.2F, -4.2F, 1.4F, 0.7F, 0.7F)
			.texOffs(110, 0).addBox(-0.35F, -14.7F, -4.9F, 0.7F, 0.7F, 0.7F)
			.texOffs(84, 0).addBox(-0.7F, -18.2F, -4.9F, 1.4F, 3.5F, 0.7F)
			.texOffs(103, 0).addBox(-0.7F, -18.9F, -4.9F, 1.4F, 0.7F, 0.7F)
			.texOffs(110, 0).addBox(-0.35F, -15.4F, -5.6F, 0.7F, 0.7F, 0.7F)
			.texOffs(84, 0).addBox(-0.7F, -18.2F, -5.6F, 1.4F, 2.8F, 0.7F)
			.texOffs(103, 0).addBox(-0.7F, -18.9F, -5.6F, 1.4F, 0.7F, 0.7F)
			.texOffs(110, 0).addBox(-0.35F, -15.4F, -6.3F, 0.7F, 0.7F, 0.7F)
			.texOffs(84, 0).addBox(-0.7F, -18.9F, -6.3F, 1.4F, 3.5F, 0.7F)
			.texOffs(103, 0).addBox(-0.7F, -19.6F, -6.3F, 1.4F, 0.7F, 0.7F)
			.texOffs(110, 0).addBox(-0.35F, -16.1F, -8.4F, 0.7F, 0.7F, 2.1F)
			.texOffs(84, 0).addBox(-0.7F, -18.9F, -8.4F, 1.4F, 2.8F, 2.1F)
			.texOffs(103, 0).addBox(-0.7F, -19.6F, -8.4F, 1.4F, 0.7F, 2.1F)
			.texOffs(110, 0).addBox(-0.35F, -16.1F, -9.1F, 0.7F, 0.7F, 0.7F)
			.texOffs(84, 0).addBox(-0.7F, -18.2F, -9.1F, 1.4F, 2.1F, 0.7F)
			.texOffs(103, 0).addBox(-0.7F, -18.9F, -9.1F, 1.4F, 0.7F, 0.7F)
			.texOffs(110, 0).addBox(-0.35F, -15.4F, -9.8F, 0.7F, 0.7F, 0.7F)
			.texOffs(84, 0).addBox(-0.7F, -18.2F, -9.8F, 1.4F, 2.8F, 0.7F)
			.texOffs(103, 0).addBox(-0.7F, -18.9F, -9.8F, 1.4F, 0.7F, 0.7F)
			.texOffs(110, 0).addBox(-0.35F, -15.4F, -10.5F, 0.7F, 0.7F, 0.7F)
			.texOffs(84, 0).addBox(-0.7F, -17.5F, -10.5F, 1.4F, 2.1F, 0.7F)
			.texOffs(103, 0).addBox(-0.7F, -18.2F, -10.5F, 1.4F, 0.7F, 0.7F)
			.texOffs(110, 0).addBox(-0.35F, -14.7F, -11.2F, 0.7F, 0.7F, 0.7F)
			.texOffs(84, 0).addBox(-0.7F, -17.5F, -11.2F, 1.4F, 2.8F, 0.7F)
			.texOffs(103, 0).addBox(-0.7F, -18.2F, -11.2F, 1.4F, 0.7F, 0.7F)
			.texOffs(110, 0).addBox(-0.35F, -14F, -11.9F, 0.7F, 0.7F, 0.7F)
			.texOffs(84, 0).addBox(-0.7F, -16.8F, -11.9F, 1.4F, 2.8F, 0.7F)
			.texOffs(103, 0).addBox(-0.7F, -17.5F, -11.9F, 1.4F, 0.7F, 0.7F)
			.texOffs(110, 0).addBox(-0.35F, -13.3F, -12.6F, 0.7F, 0.7F, 0.7F)
			.texOffs(84, 0).addBox(-0.7F, -16.8F, -12.6F, 1.4F, 3.5F, 0.7F)
			.texOffs(103, 0).addBox(-0.7F, -17.5F, -12.6F, 1.4F, 0.7F, 0.7F)
			.texOffs(110, 0).addBox(-0.35F, -11.9F, -13.3F, 0.7F, 0.7F, 0.7F)
			.texOffs(84, 0).addBox(-0.7F, -16.1F, -13.3F, 1.4F, 4.2F, 0.7F)
			.texOffs(103, 0).addBox(-0.7F, -16.8F, -13.3F, 1.4F, 0.7F, 0.7F)
			.texOffs(110, 0).addBox(-0.35F, -10.5F, -14F, 0.7F, 0.7F, 0.7F)
			.texOffs(84, 0).addBox(-0.7F, -16.1F, -14F, 1.4F, 5.6F, 0.7F)
			.texOffs(103, 0).addBox(-0.7F, -16.8F, -14F, 1.4F, 0.7F, 0.7F)
			.texOffs(70, 0).addBox(-0.35F, -9.1F, -14.7F, 0.7F, 0.7F, 0.7F)
			.texOffs(70, 0).addBox(-0.7F, -15.4F, -14.7F, 1.4F, 6.3F, 0.7F)
			.texOffs(70, 0).addBox(-0.7F, -16.1F, -14.7F, 1.4F, 0.7F, 0.7F)
			.texOffs(70, 0).addBox(-0.35F, -7.7F, -15.4F, 0.7F, 0.7F, 0.7F)
			.texOffs(70, 0).addBox(-0.7F, -14.7F, -15.4F, 1.4F, 7F, 0.7F)
			.texOffs(70, 0).addBox(-0.7F, -15.4F, -15.4F, 1.4F, 0.7F, 0.7F)
			.texOffs(70, 0).addBox(-0.35F, -6.3F, -16.1F, 0.7F, 0.7F, 0.7F)
			.texOffs(70, 0).addBox(-0.7F, -14F, -16.1F, 1.4F, 7.7F, 0.7F)
			.texOffs(70, 0).addBox(-0.7F, -14.7F, -16.1F, 1.4F, 0.7F, 0.7F),
			PartPose.offset(0F, 0F, 0F));

		PartDefinition left_arm = root.addOrReplaceChild("left_arm", CubeListBuilder.create()
			.texOffs(32, 48).addBox(-1F, -2F, -2F, 4F, 12F, 4F)
			.texOffs(48, 48).addBox(-1F, -2F, -2F, 4F, 12F, 4F, new CubeDeformation(0.25F)),
			PartPose.offset(5F, 2F, 0F));

		PartDefinition right_leg = root.addOrReplaceChild("right_leg", CubeListBuilder.create()
			.texOffs(0, 16).addBox(-2F, 0F, -2F, 4F, 12F, 4F)
			.texOffs(0, 32).addBox(-2F, 0F, -2F, 4F, 12F, 4F, new CubeDeformation(0.25F)),
			PartPose.offset(-1.9F, 12F, 0F));

		PartDefinition left_leg = root.addOrReplaceChild("left_leg", CubeListBuilder.create()
			.texOffs(16, 48).addBox(-2F, 0F, -2F, 4F, 12F, 4F)
			.texOffs(0, 48).addBox(-2F, 0F, -2F, 4F, 12F, 4F, new CubeDeformation(0.25F)),
			PartPose.offset(1.9F, 12F, 0F));

		return LayerDefinition.create(mesh, 128, 128);
	}
}
