"""Insert corrective keyframes so the scythe never passes through his body or the ground.

    python tools/autofix.py <anim> [anim ...]        prints the repaired key list (paste it into animations.py)

Finds the worst tick over four possible start angles of the idle twirl, nudges the pose at that tick
(arms, scythe, body, head) with tools/collide.tune and inserts it as a new key; repeats until clean.
"""
import copy, math, os, sys

ROOT = os.environ.get("ENTITY303_ROOT", "C:/rb")
sys.path.insert(0, os.path.join(ROOT, "tools"))
import animations as A  # noqa: E402
import collide as C  # noqa: E402

STARTS = (0.0, 1.57, 3.14, 4.71)
FREE = [("right_arm", 0), ("right_arm", 1), ("right_arm", 2), ("scythe_pivot", 0), ("scythe_pivot", 1),
        ("scythe_pivot", 2), ("scythe", 2), ("body", 0), ("head", 0), ("left_arm", 0), ("left_arm", 2)]


def tick_costs(name, margin):
    anim = A.ANIMS[name]
    out = []
    for t in range(0, anim["duration"] + 1):
        ch, _ = A.sample(anim, t)
        worst, ground = 0.0, 0.0
        for s0 in STARTS:
            tot, w, g = C.evaluate(ch, A.spin_at(name, t, s0), margin)
            worst, ground = max(worst, w), max(ground, g)
        if name in A.NO_GROUND_CHECK:
            ground = 0.0
        out.append((worst + 2 * ground, t))
    return out


def fix(name, threshold=0.35, margin=0.5, max_new=30):
    C.IGNORE_GROUND = name in A.NO_GROUND_CHECK      # spawn / death: parts of him are meant to be below the floor
    anim = copy.deepcopy(A.ANIMS_AUTHORED[name])
    A.ANIMS[name] = anim            # tick_costs() reads the animation that is being repaired
    for _ in range(max_new):
        costs = tick_costs(name, 0.0)
        cost, t = max(costs)
        if cost < threshold:
            break
        ch, sp = A.sample(anim, t)
        pose = {p: ch[i * 3:i * 3 + 3] for i, p in enumerate(A.PARTS)}
        pose["off"] = ch[len(A.PARTS) * 3:]
        spins = [A.spin_at(name, t, s0) for s0 in STARTS]
        new, tt, gg = C.tune(pose, FREE, spins, margin=margin, reach=70.0, stiffness=0.01)
        key = {p: [round(v, 1) for v in new[p]] for p in A.PARTS}
        key["off"] = [round(v, 1) for v in new["off"]]
        key["spin"] = [round(sp[0], 3), round(sp[1], 3)]
        key["t"] = float(t)
        keys = [k for k in anim["keys"] if float(k["t"]) != float(t)]
        keys.append(key)
        keys.sort(key=lambda k: float(k["t"]))
        anim["keys"] = keys
        print(f"  fixed t={t}: cost {cost:.1f} -> overlap {tt:.1f} ground {gg:.1f}", file=sys.stderr)
    return anim


def dump(name, anim):
    print(f'    "{name}": dict(id={anim["id"]}, duration={anim["duration"]}, loop={anim["loop"]}, events={anim["events"]}, keys=[')
    for k in anim["keys"]:
        parts = []
        for p in A.PARTS + ["off"]:
            if p in k:
                parts.append(f"{p}={[round(float(v), 1) for v in k[p]]}")
        if "spin" in k:
            parts.append(f"spin={[round(float(v), 3) for v in k['spin']]}")
        print(f"        dict(t={k['t']}, " + ", ".join(parts) + "),")
    print("    ]),")


def _fix_one(name):
    a = A.ANIMS_AUTHORED[name]
    return name, (a if a["loop"] else fix(name))   # the looping idles twirl through every angle: authored as is


def write_all(path, only=None):
    """Writes animations_fixed.py. `only` = animation names to repair again; the others keep the keys of the
    existing animations_fixed.py (it is much faster when just one or two animations were edited)."""
    from concurrent.futures import ProcessPoolExecutor
    names = [n for n, _ in sorted(A.ANIMS_AUTHORED.items(), key=lambda kv: kv[1]["id"])]
    todo = [n for n in names if only is None or n in only or n not in A.ANIMS]
    # every animation is repaired independently: use all the cores
    with ProcessPoolExecutor() as pool:
        repaired = dict(pool.map(_fix_one, todo))
    for n in names:
        repaired.setdefault(n, A.ANIMS[n])
    out = ["# GENERATED by tools/autofix.py from tools/animations.py - do not edit by hand.",
           "# The authored keyframes plus corrective keys that keep the scythe out of his body and the ground.",
           "ANIMS = {"]
    for name in names:
        fixed = repaired[name]
        out.append(f'    "{name}": dict(id={fixed["id"]}, duration={fixed["duration"]}, loop={fixed["loop"]}, events={fixed["events"]}, keys=[')
        for k in fixed["keys"]:
            parts = []
            for p in A.PARTS + ["off"]:
                if p in k:
                    parts.append(f"{p}={[round(float(v), 2) for v in k[p]]}")
            if "spin" in k:
                parts.append(f"spin={[round(float(v), 4) for v in k['spin']]}")
            out.append(f"        dict(t={float(k['t'])}, " + ", ".join(parts) + "),")
        out.append("    ]),")
    out.append("}")
    with open(path, "w", encoding="utf-8", newline=chr(10)) as fh:
        fh.write(chr(10).join(out) + chr(10))


if __name__ == "__main__":
    if sys.argv[1:2] == ["--write"]:
        write_all(os.path.join(ROOT, "tools", "animations_fixed.py"), only=sys.argv[2:] or None)
    else:
        for n in sys.argv[1:]:
            print(f"== {n}", file=sys.stderr)
            dump(n, fix(n))
